### PR TITLE
Embed etcd into nsqlookupd

### PR DESCRIPTION
**Pull request by yuzhichang**

### CODE REVIEW

**Comment by absolute8511** [comment]
Maybe we need a config to allow the user to decide whether using remote etcd or embed one.

**Comment by yuzhichang** [comment]
Commit [e782cfa](https://github.com/youzan/nsq/pull/45/commits/e782cfa1c40ac399d1b374fbec288eb6645d1cf0) allow the user to decide whether using remote etcd or embed one. 

If the remote etcd cluster is dedicated to nsq, we can take these etcd node down one by one according to [this guide](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/clustering.md). Otherwise an short shutdown of nsqlookupd is needed.

**Comment by absolute8511** [comment]
Can you add a detail operation document in here to give a guide for the upgrade: 
 https://github.com/youzan/nsq/blob/master/doc/upgrade-notes.md

**Comment by yuzhichang** [comment]
upgrade-notes.md is for official versions. It's not appropriate do edit it inside this pull request.

**Comment by absolute8511** [comment]
@yuzhichang  
You can just add a new title  as `upgrade to embed etcd`.

**Pull request closed without merging**
